export const MOCK_SEMESTERS = [
  {
    id: "-M6vO_oW4hzj9B2_d-ie",
    name: "Fall 2020",
    average: 85,
    grade: "A+",
    gpa: 4.0,
    numCourses: 1,
  },
  {
    id: "-M70HLw6GQAkUS913_zX",
    name: "Summer 2020",
    average: 75,
    grade: "B",
    gpa: 3.0,
    numCourses: 4,
  },
  {
    id: "-M71HLw6GQAkUS924_zV",
    name: "Winter 2020",
    average: 65,
    grade: "C-",
    gpa: 2.0,
    numCourses: 3,
  },
];

export const MOCK_COURSE_GRADE = {
  grade: "B",
  average: 69,
  gpa: 3.0
}

export const MOCK_COURSES = [
  {
    id: "-M6v_lHIIfdMhcZykqOp",
    instructor: "",
    name: "VPMA93",
    numCategories: 5,
    passFail: true,
    semesterKey: "-M6vO_oW4hzj9B2_d-ie",
  },
  {
    id: "-M6vacBj3PKoIAZPW96F",
    instructor: "",
    name: "CSCA67",
    numCategories: 5,
    passFail: false,
    semesterKey: "-M6vO_oW4hzj9B2_d-ie",
  },
  {
    id: "-M6vb5541Udk87CMB-3r",
    instructor: "",
    name: "LINA01",
    numCategories: 7,
    passFail: false,
    semesterKey: "-M6vO_oW4hzj9B2_d-ie",
  },
  {
    id: "-M6vba8U_AO4_nSYoGEf",
    instructor: "Natalia Breuss",
    name: "MATA31",
    numCategories: 4,
    passFail: false,
    semesterKey: "-M6vO_oW4hzj9B2_d-ie",
  },
  {
    id: "-M6veHKQRO2Msounat99",
    instructor: "Nick Cheng",
    name: "CSCA08",
    numCategories: 5,
    passFail: false,
    semesterKey: "-M6vO_oW4hzj9B2_d-ie",
  },
  {
    id: "-M71I-_dPkAQSBfJm3zm",
    instructor: "Kaidi Ye",
    name: "MATA22",
    numCategories: 2,
    passFail: true,
    semesterKey: "-M6vO_oW4hzj9B2_d-ie",
  },
  {
    id: "-M71LdiNxl3m_Bzdy5pi",
    instructor: "Kathleen Smith",
    name: "MATA37",
    numCategories: 4,
    passFail: true,
    semesterKey: "-M6vO_oW4hzj9B2_d-ie",
  },
  {
    id: "-M71NicZp9zH0paKaFpm",
    instructor: "Paco Estrada",
    name: "CSCA48",
    numCategories: 5,
    passFail: true,
    semesterKey: "-M6vO_oW4hzj9B2_d-ie",
  },
  {
    id: "-M71Q7AE_Q-D6xTkRsiF",
    instructor: "Lindsey Shorser",
    name: "CSC207",
    numCategories: 4,
    passFail: false,
    semesterKey: "-M6vO_oW4hzj9B2_d-ie",
  },
  {
    id: "-M71RKmjA0gh81pF7Ci5",
    instructor: "Camelia Karimian Pour",
    name: "MATB24",
    numCategories: 12,
    passFail: false,
    semesterKey: "-M6vO_oW4hzj9B2_d-ie",
  },
  {
    id: "-M71RxOjgd3UGMuCSIdt",
    instructor: "Xiao Jie",
    name: "MATB41",
    numCategories: 3,
    passFail: false,
    semesterKey: "-M6vO_oW4hzj9B2_d-ie",
  },
  {
    id: "-M764HL8r-vxl5pSzY5y",
    instructor: "Albert Lai",
    name: "CSCB09",
    numCategories: 5,
    passFail: false,
    semesterKey: "-M6vO_oW4hzj9B2_d-ie",
  },
  {
    id: "-MGp2Ys4B1HlAeDzWRwl",
    instructor: "Ilir Dema",
    name: "CSCC01",
    numCategories: 3,
    passFail: false,
    semesterKey: "-M6vO_oW4hzj9B2_d-ie",
  },
]
